### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ninjatrac** [ALSchwalm/foresight#6]
Hello, I'm new here and in programming (I'm still a student) so maybe I'm doing something wrong... I cloned the folder trough the URL, but when I try to run the setup the terminal windows appear and disappear and then nothing happens... (I also tried to launch it with Python 3.6) Thank you very much for the help!

**Comment by ALSchwalm** [comment]
It sounds like you're using windows. If that's the case, you can't just click the setup.py file, you will need to open a command prompt and run the command `python setup.py install` in the directory where you cloned the repository. If windows says that it can't find 'python', you should add it to your path as described [here](https://docs.python.org/3/using/windows.html#excursus-setting-environment-variables).

**Comment by ninjatrac** [comment]
Thank you very much! I managed to install it running the command `py setup.py install`. I don't know why but it works without adding the path, writing only `py` instead of `python`. Thank you again!

**Comment by ALSchwalm** [comment]
Good to hear. I'll close this issue, but feel free to open another if you encounter other problems.
